### PR TITLE
Updated Traditional Chinese translations

### PR DESCRIPTION
**Pull request by Jerry23011**
Optimized translations based on the terms from Apple.

- "%0 節能核心" for "Number of e-cores"
- "節能核心" for "Efficiency cores"

Added new translations

- "核心數" for "Cores"
- "電流" for "Current"
- "能耗" for "Energy"
- "統一比例" for "Common scale"
- "自動檢測" for "Autodetection"
- "圖示內百分比" for "Percentage inside the icon"
- “小工具啟動臨界點“ for ”Widget activation threshold“

### CODE REVIEW

**Comment by jrthsr700tmax** [comment]
Thanks for your contribution, there is a little Chinese Character need to correct.

The Chinese Character "內" is the correct one for Traditional Chinese (in particular in the ROC Taiwan) instead of "内" of translation item "圖示内百分比" for "Percentage inside the icon".

The correct translation item is "圖示內百分比". May you help to correct this wrong translation? Thank you.

**Comment by Jerry23011** [comment]
Hi! My friend in Taiwan, pleasure to meet you, I'm from Liaoning!
Thank you very much for reminding me of the correct character「內」This branch has been updated.
Hope we can cooperate again in the future! 😄

**Comment by Cedric-Lv** [comment]
> Thanks for your contribution, there is a little Chinese Character need to correct.
> 
> The Chinese Character "內" is the correct one for Traditional Chinese (in particular in the ROC Taiwan) instead of "内" of translation item "圖示内百分比" for "Percentage inside the icon".
> 
> The correct translation item is "圖示內百分比". May you help to correct this wrong translation? Thank you.

Greetings, Chinese Taipei friend, it’s good to correct the mistake in the file, but could you stop bringing up political issues in your comments?

I see that you are an employee of the Taipei government; however, it is not your excuse to express your own political stance on a platform like GitHub. (There’s simply no need to add those content in the parentheses) By doing this, you are being offensive and distracting.

More code, less politics. Thank you! @jrthsr700tmax 🥹

**Comment by jrthsr700tmax** [comment]
> > Thanks for your contribution, there is a little Chinese Character need to correct.
> > 
> > The Chinese Character "內" is the correct one for Traditional Chinese (in particular in the ROC Taiwan) instead of "内" of translation item "圖示内百分比" for "Percentage inside the icon".
> > 
> > The correct translation item is "圖示內百分比". May you help to correct this wrong translation? Thank you.
> 
> Greetings, Chinese Taipei friend, it’s good to correct the mistake in the file, but could you stop bringing up political issues in your comments?
> 
> I see that you are an employee of the Taipei government; however, it is not your excuse to express your own political stance on a platform like GitHub. (There’s simply no need to add those content in the parentheses) By doing this, you are being offensive and distracting.
> 
> More code, less politics. Thank you! @jrthsr700tmax 🥹

I'm very glad that you bring this up and thanks for your reminding. Actually I didn't intention to talk about politics issues. I just want to see that the translation may be more better. In the comments which I left yesterday, I didn't said anything about politics issues. If you care about the term "the ROC Taiwan", I only can say the ROC Taiwan is my country, I need to say so.

Everyone lives in different country has different national identity, as a Taiwanese, I identify with national identity of Taiwan and that is naturally.

You have your own national identity, and I also have my own national identity. This is not affecting the mind that we want to make this project better, and this reflects that GitHub is a diversity community. I hope you can understand that ☺️. @Cedric-Lv

**Comment by DaJiaHaoWoShiSZ** [comment]
Agree with @Cedric-Lv  , let's not talk about politics on GitHub and don't even start to make comments that may do harm. Taiwan issue is a historic remnant, but it will be eventually solved. Before that, let's respect each other and continue to be amazing contributors of this community

**Comment by Cedric-Lv** [comment]
> > > Thanks for your contribution, there is a little Chinese Character need to correct.
> > > 
> > > The Chinese Character "內" is the correct one for Traditional Chinese (in particular in the ROC Taiwan) instead of "内" of translation item "圖示内百分比" for "Percentage inside the icon".
> > > 
> > > The correct translation item is "圖示內百分比". May you help to correct this wrong translation? Thank you.
> > 
> > Greetings, Chinese Taipei friend, it’s good to correct the mistake in the file, but could you stop bringing up political issues in your comments?
> > 
> > I see that you are an employee of the Taipei government; however, it is not your excuse to express your own political stance on a platform like GitHub. (There’s simply no need to add those content in the parentheses) By doing this, you are being offensive and distracting.
> > 
> > More code, less politics. Thank you! @jrthsr700tmax 🥹
> 
> I'm very glad that you bring this up and thanks for your reminding. Actually I didn't intention to talk about politics issues. I just want to see that the translation may be more better. In the comments which I left yesterday, I didn't said anything about politics issues. If you care about the term "the ROC Taiwan", I only can say the ROC Taiwan is my country, I need to say so.
> 
> Everyone lives in different country has different national identity, as a Taiwanese, I identify with national identity of Taiwan and that is naturally.
> 
> You have your own national identity, and I also have my own national identity. This is not affecting the mind that we want to make this project better, and this reflects that GitHub is a diversity community.
> 
> I think that you can understand that ☺️. @Cedric-Lv 

	Mr. Wang, You are still bringing up political issue, probably because you have to do that since you are a government official of Taipei.

Let me make this clear: the so called “ROC Taiwan” is not a country. “Taiwan” has never been a country, and it will never be. “ROC”, short for “Republic of China”, is no longer recognized by the United Nation and the international society after 1971. You have to learn to accept the reality.

Like I said, GitHub is a place for code, not for politics, we seek common ground while reserving differences.
 Nevertheless, I would still want to thank you for making this project better so that Chinese all across the world may use this wonderful app.

**Comment by Cedric-Lv** [comment]
> > > Thanks for your contribution, there is a little Chinese Character need to correct.
> > > 
> > > The Chinese Character "內" is the correct one for Traditional Chinese (in particular in the ROC Taiwan) instead of "内" of translation item "圖示内百分比" for "Percentage inside the icon".
> > > 
> > > The correct translation item is "圖示內百分比". May you help to correct this wrong translation? Thank you.
> > 
> > Greetings, Chinese Taipei friend, it’s good to correct the mistake in the file, but could you stop bringing up political issues in your comments?
> > 
> > I see that you are an employee of the Taipei government; however, it is not your excuse to express your own political stance on a platform like GitHub. (There’s simply no need to add those content in the parentheses) By doing this, you are being offensive and distracting.
> > 
> > More code, less politics. Thank you! @jrthsr700tmax 🥹
> 
> I'm very glad that you bring this up and thanks for your reminding. Actually I didn't intention to talk about politics issues. I just want to see that the translation may be more better. In the comments which I left yesterday, I didn't said anything about politics issues. If you care about the term "the ROC Taiwan", I only can say the ROC Taiwan is my country, I need to say so.
> 
> Everyone lives in different country has different national identity, as a Taiwanese, I identify with national identity of Taiwan and that is naturally.
> 
> You have your own national identity, and I also have my own national identity. This is not affecting the mind that we want to make this project better, and this reflects that GitHub is a diversity community.
> 
> I think that you can understand that ☺️. @Cedric-Lv 

Mr. Wang, You are still bringing up political issue, probably because you have to do that since you are a government official of Taipei.

Let me make this clear: the so called “ROC Taiwan” is not a country. “Taiwan” has never been a country, and it will never be. “ROC”, short for “Republic of China”, is no longer recognized by the United Nation and the international society after 1971. You have to learn to accept the reality.

Like I said, GitHub is a place for code, not for politics, we seek common ground while reserving differences.
 Nevertheless, I would still want to thank you for making this project better so that Chinese all across the world may use this wonderful app.

**Comment by Jerry23011** [comment]
OK, thank you @Cedric-Lv , I see the problem, didn't notice it when I first read the comment.
Please do not include any controversial speeches under this PR. I would appreciate that! @jrthsr700tmax

**Pull request merged**
