### PR TITLE
Updating missing translations and fixing lenght of “Full charged"

### PR DESCRIPTION
**Pull request by kevinm6**

### CODE REVIEW

**Comment by exelban** [comment]
Thanks.

**Comment by Angelk90** [comment]
@kevinm6 : I've made some changes compare them to yours and let me know.

```swift
//
//  Localizable.strings
//  Stats
//
//  Created by Serhiy Mytrovtsiy on 27/08/2020.
//  Using Swift 5.0.
//  Running on macOS 10.15.
//
//  Copyright © 2020 Serhiy Mytrovtsiy. All rights reserved.
//

// Modules
"CPU" = "CPU";
"Open CPU settings" = "Apri impostazioni CPU";
"GPU" = "GPU";
"Open GPU settings" = "Apri impostazioni GPU";
"RAM" = "RAM";
"Open RAM settings" = "Apri impostazioni RAM";
"Disk" = "Disco";
"Open Disk settings" = "Apri impostazioni disco";
"Sensors" = "Sensori";
"Open Sensors settings" = "Apri impostazioni Sensori";
"Fans" = "Ventole";
"Open Fans settings" = "Apri impostazioni Ventole";
"Network" = "Rete";
"Open Network settings" = "Apri impostazioni Rete";
"Battery" = "Batteria";
"Open Battery settings" = "Apri impostazioni Batteria";
"Bluetooth" = "Bluetooth";
"Open Bluetooth settings" = "Apri impostazioni Bluetooth";

// Words
"Unknown" = "Sconosciuto";
"Version" = "Versione";
"Processor" = "Processore";
"Memory" = "Memoria";
"Graphics" = "Grafica";
"Close" = "Chiudi";
"Download" = "Scarica";
"Install" = "Installa";
"Cancel" = "Annulla";
"Unavailable" = "Non disponibile";
"Yes" = "Si";
"No" = "No";
"Automatic" = "Automatico";
"Manual" = "Manuale";
"None" = "Nessuna";
"Dots" = "Punti";
"Arrows" = "Frecce";
"Characters" = "Caratteri";
"Short" = "Corto";
"Long" = "Lungo";
"Statistics" = "Statistiche";
"Max" = "Max";
"Min" = "Min";
"Reset" = "Reset";
"Alignment" = "Allineamento";
"Left alignment" = "Sinistra";
"Center alignment" = "Centro";
"Right alignment" = "Destra";
"Dashboard" = "Dashboard";

// Alerts
"New version available" = "Nuova versione disponibile";
"Click to install the new version of Stats" = "Clicca per installare la nuova versione di Stats";
"Successfully updated" = "Aggiornato con successo";
"Stats was updated to v" = "Stats è stato aggiornato a v%0";

// Settings
"Open Activity Monitor" = "Apri Monitoraggio Attività";
"Report a bug" = "Segnala un bug";
"Support the application" = "Supporta l'applicazione";
"Close application" = "Chiudi applicazione";
"Open application settings" = "Apri le impostazioni dell'applicazione";
"Open dashboard" = "Apri dashboard";

// Application settings
"Update application" = "Aggiorna applicazione";
"Check for updates" = "Controlla aggiornamenti";
"At start" = "All'avvio";
"Once per day" = "Una volta al giorno";
"Once per week" = "Una volta a settimana";
"Once per month" = "Una volta al mese";
"Never" = "Mai";
"Check for update" = "Controlla aggiornamento";
"Show icon in dock" = "Mostra icona nel dock";
"Start at login" = "Avvia al login";

// Dashboard
"Serial number" = "Numero di serie";
"Uptime" = "Tempo di attività";

// Update
"The latest version of Stats installed" = "L'ultima versione di Stats è installata";
"Downloading..." = "Download in corso...";
"Current version: " = "Versione corrente: ";
"Latest version: " = "Ultima versione: ";

// Widgets
"Color" = "Colore";
"Label" = "Etichetta";
"Box" = "Scatola";
"Frame" = "Riquadro";
"Value" = "Valore";
"Colorize" = "Colora";
"Colorize value" = "Valore colorato";
"Additional information" = "Informazioni aggiuntive";
"Reverse values order" = "Inverti ordine valori";
"Base" = "Base";
"Display mode" = "Modalità di visualizzazione";
"One row" = "Una riga";
"Two rows" = "Due righe";
"Mini widget" = "Mini";
"Line chart widget" = "Grafico a linee";
"Bar chart widget" = "Grafico a barre";
"Pie chart widget" = "Grafico a torta";
"Network chart widget" = "Grafico rete";
"Speed widget" = "Velocità";
"Battery widget" = "Batteria";
"Text widget" = "Testo";
"Memory widget" = "Memoria";
"Static width" = "Larghezza fissa";

// Module Kit
"Open module settings" = "Apri impostazioni modulo";
"Select widget" = "Seleziona il widget %0";
"Open widget settings" = "Open widget settings";
"Update interval" = "Intervallo di aggiornamento";
"Usage history" = "Cronologia d'uso";
"Details" = "Dettagli";
"Top processes" = "Processi principali";
"Pictogram" = "Pittogramma";

// Modules
"Number of top processes" = "Numero di processi principali";
"Update interval for top processes" = "Intervallo d'aggiornamento per processi principali";

// CPU
"CPU usage" = "Utilizzo CPU";
"CPU temperature" = "Temperatura CPU";
"CPU frequency" = "Frequenza CPU";
"System" = "Sistema";
"User" = "Utente";
"Idle" = "Inattiva";
"Show usage per core" = "Mostra uso per core";
"Show hyper-threading cores" = "Mostra cores hyper-threading";
"Split the value (System/User)" = "Dividi il valore (Sistema/Utente)";
"Scheduler limit" = "Limite di pianificazione";
"Speed limit" = "Limite velocità";
"Average load" = "Carico medio";
"1 minute" = "1 minuto";
"5 minutes" = "5 minuti";
"15 minutes" = "15 minuti";

// GPU
"GPU to show" = "GPU da mostrare";
"Show GPU type" = "Mostra il tipo di GPU";
"GPU enabled" = "GPU abilitato";
"GPU disabled" = "GPU disabilitato";
"GPU temperature" = "Temperatura GPU";
"GPU utilization" = "Utilizzo GPU";
"Vendor" = "Venditore";
"Model" = "Modello";
"Status" = "Stato";
"Active" = "Attivo";
"Non active" = "Non attivo";
"Fan speed" = "Velocità ventole";
"Core clock" = "Clock core";
"Memory clock" = "Clock memoria";
"Utilization" = "Utilizzo";

// RAM
"Memory usage" = "Memoria utilizzata";
"Memory pressure" = "Compressione memoria";
"Total" = "Totale";
"Used" = "Usata";
"App" = "App";
"Wired" = "Cablata";
"Compressed" = "Compressa";
"Free" = "Libera";
"Swap" = "Scambiata";
"Split the value (App/Wired/Compressed)" = "Dividi il valore (App/Wired/Compressa)";

// Disk
"Show removable disks" = "Mostra dischi rimovibili";
"Used disk memory" = "Usato %0 su %1";
"Free disk memory" = "Libera %0 su %1";
"Disk to show" = "Disco da mostrare";
"Open disk" = "Apri disco";
"Switch view" = "Cambia visualizzazione";

// Sensors
"Temperature unit" = "Unità di temperatura";
"Celsius" = "Celsius";
"Fahrenheit" = "Fahrenheit";
"Save the fan speed" = "Salva la velocità delle ventole";

// Network
"Uploading" = "Upload";
"Downloading" = "Download";
"Public IP" = "IP Pubblico";
"Local IP" = "IP Locale";
"Interface" = "Interfaccia";
"Physical address" = "Indirizzo fisico";
"Refresh" = "Aggiorna";
"Click to copy public IP address" = "Clicca per copiare l'IP pubblico";
"Click to copy local IP address" = "Clicca per copiare l'IP locale";
"Click to copy wifi name" = "Clicca per copiare il nome del wifi";
"Click to copy mac address" = "Clicca per copiare l'indirizzo mac";
"No connection" = "Nessuna connessione";
"Network interface" = "Interfaccia di rete";
"Total download" = "Download totale";
"Total upload" = "Upload totale";
"Reader type" = "Tipo di lettore";
"Interface based" = "Interfaccia";
"Processes based" = "Processi";
"Reset data usage" = "Ripristina l'utilizzo dei dati";

// Battery
"Level" = "Livello";
"Source" = "Sorgente";
"AC Power" = "AC Power";
"Battery Power" = "Batteria";
"Time" = "Tempo";
"Health" = "Vita";
"Amperage" = "Amperaggio";
"Voltage" = "Voltaggio";
"Cycles" = "Numero di cicli";
"Temperature" = "Temperatura";
"Power adapter" = "Alimentatore di corrente";
"Power" = "Corrente";
"Is charging" = "In carica";
"Time to discharge" = "Tempo di scarica";
"Time to charge" = "Tempo di carica";
"Calculating" = "Calcolo in corso";
"Fully charged" = "Carica";
"Not connected" = "Non connesso";
"Low level notification" = "Notifica livello basso";
"High level notification" = "Notifica livello alto";
"Low battery" = "Batteria scarica";
"High battery" = "Batteria carica";
"Battery remaining" = "%0% rimanente";
"Battery remaining to full charge" = "%0% per carica completa";
"Percentage" = "Percentuale";
"Percentage and time" = "Percentuale e tempo";
"Time and percentage" = "Tempo e percentuale";
"Time format" = "Formato del tempo";
"Hide additional information when full" = "Nascondi informazioni addizionali quando piena";
"Last charge" = "Ultima carica";

// Bluetooth
"Battery to show" = "Batteria da mostrare";

// Colors
"Based on utilization" = "Basato sull'utilizzo";
"Based on pressure" = "Basato sulla pressione";
"System accent" = "Accento di sistema";
"Monochrome accent" = "Accento monocromatico";
"Clear" = "Chiaro";
"White" = "Bianco";
"Black" = "Nero";
"Gray" = "Grigio";
"Second gray" = "Secondo grigio";
"Dark gray" = "Grigio scuro";
"Light gray" = "Grigio chiaro";
"Red" = "Rosso";
"Second red" = "Secondo rosso";
"Green" = "Verde";
"Second green" = "Secondo verde";
"Blue" = "Blu";
"Second blue" = "Secondo blu";
"Yellow" = "Giallo";
"Second yellow" = "Secondo giallo";
"Orange" = "Arancione";
"Second orange" = "Secondo arancione";
"Purple" = "Viola";
"Second purple" = "Secondo viola";
"Brown" = "Marrone";
"Second brown" = "Secondo marrone";
"Cyan" = "Ciano";
"Magenta" = "Magenta";
"Pink" = "Rosa";
"Teal" = "Verde acqua";
```

**Comment by kevinm6** [comment]
Done! 
Check the [https://github.com/exelban/stats/pull/638/commits/4099580a344f2476d99a3e9101e1c121dca9b98d](new commit) to see if all the changes are correct!

**Comment by Angelk90** [comment]
@kevinm6 : Perfect.

P.s.
Is there a way to contact you privately, I don't know on Twitter?

**Pull request merged**
