### PR TITLE
Added Language: English Australian

### PR DESCRIPTION
**Pull request by Will-Georges**
Added English Australian Localisation.

Feel free to let me know if I need to make any changes.

### CODE REVIEW

**Comment by exelban** [comment]
Hi. Sorry for the question, but what the difference between English and English Australian?
I take a quick look and find no difference in the translation.

**Comment by Will-Georges** [comment]
There aren't many differences:

- Color is colour
- Utilization is utilisation
- Gray is grey

If it not worth the change then don't bother, but they are the main changes.

**Comment by Will-Georges** [comment]
I just thought that since you also have en-GB which is similar, you may as well have en-AU as well.

**Comment by exelban** [comment]
It's not a problem to add, but will be problem to support. If you ok with monitor and support it ok, otherwise I don't think it's worth to add that for 3 words (which also very similar)

**Comment by Will-Georges** [comment]
When you say support it, do you mean when new words and things are added, or what exactly?

If it is just for when new words come then I can do that. I use the app all the time so I'm happy to help.

**Comment by Will-Georges** [comment]
And also I am a bit of a code noob so I don't know how to resolve the conflict. Like I see what the problem is, but I don't know how to fix it through GitHub, if you could either do it or teach me please?

**Pull request merged**
