### PR TITLE
📝 Greek Language Translation

### PR DESCRIPTION
**Pull request by sudoxcess**
Hi there! It was a pleasure of mine to contribute to your project by translating the app to Greek. Every translation is accurate and compatible with macOS words in Greek! Also, I didn't know how to name the file so I named it just "gr", sorry if there's a problem with that.

### CODE REVIEW

**Comment by exelban** [comment]
Hi, thanks for your contribution.
Can I add you to the readme as a Greek translation contributor?

**Comment by sudoxcess** [comment]
Hello. Sure why not!

On 9 Jun 2022, at 14:05, Serhiy Mytrovtsiy ***@***.******@***.***>> wrote:



Hi, thanks for your contribution.
Can I add you to the readme as a Greek translation contributor?

**Comment by exelban** [comment]
I will add the missing integration for the translation.

**Comment by sudoxcess** [comment]
Sorry I’m new on GitHub, I don’t know how to work with it yet..

On 9 Jun 2022, at 17:42, Serhiy Mytrovtsiy ***@***.******@***.***>> wrote:



I will add the missing integration for the translation.

**Comment by exelban** [comment]
No problem)
Thanks for your contribution.

**Pull request merged**
