### PR TITLE
Update Italian localization

### PR DESCRIPTION
**Pull request by kevinm6**

### CODE REVIEW

**Comment by Angelk90** [comment]
Hi @kevinm6 , I don't know if it's a problem but I get the following result when the battery is fully charged: 
Schermata 2021-09-20 alle 21 33 27

https://github.com/exelban/stats/blob/master/Stats/Supporting%20Files/it.lproj/Localizable.strings#L236

**Comment by kevinm6** [comment]
> Hi @kevinm6 , I don't know if it's a problem but I get the following result when the battery is fully charged: 
> 
> Schermata 2021-09-20 alle 21 33 27
> 
> 
> 
> https://github.com/exelban/stats/blob/master/Stats/Supporting%20Files/it.lproj/Localizable.strings#L236


Thank you @Angelk90 for show me the issue, I'll fix it soon with just "Carica".

**Comment by Angelk90** [comment]
@kevinm6 : I guess it cuts the text, right?

**Comment by kevinm6** [comment]
Yes exactly. 
I’m doing it right now, the we just have to wait @exelban to merge the fix.

**Comment by Angelk90** [comment]
@kevinm6 : 
I also point out this:
https://github.com/exelban/stats/blob/master/Stats/Supporting%20Files/it.lproj/Localizable.strings#L119

Then I noticed that texts like these are not translated: 

Disabled:
Schermata 2021-09-20 alle 22 12 14

Fan #Number:
Schermata 2021-09-20 alle 22 16 48

**Pull request merged**
