### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by gmcinalli**

### CODE REVIEW

**Comment by exelban** [comment]
Hi.
Thanks for the translation. Can I add you as a contributor to this translation?

I will merge it on Sunday. Before releasing the new version.

**Comment by gmcinalli** [comment]
Of course yes!

Il giorno lun 9 nov 2020 alle ore 10:41 Serhiy Mytrovtsiy <
notifications@github.com> ha scritto:

**Comment by gmcinalli** [comment]
Yes, of course!

**Comment by exelban** [comment]
Hi. Could I ask you to add a few new words to the translation?
[Link to the changes](https://github.com/exelban/stats/commit/b843ff4cbf5cbbf25f98eb79a384dfcf8ded45b7#diff-4bb5109982fee530c8b79c3735eea13259b5c270186904c4bf8d3946e136a2dc).

One word in the `Words` section. And two in the `Network`. Thanks

**Comment by exelban** [comment]
Also, add please a translation in the `Battery` section of `Hide additional information if full`.

**Comment by exelban** [comment]
And [one sentence](https://github.com/exelban/stats/commit/6069ea23e8ff69355fea71e688635c982640e07e#diff-4bb5109982fee530c8b79c3735eea13259b5c270186904c4bf8d3946e136a2dc) in the `Battery` section.

**Comment by gmcinalli** [comment]
Sure!

**Comment by gmcinalli** [comment]
@exelban Done!

**Comment by exelban** [comment]
Thanks

**Comment by gmcinalli** [comment]
@exelban You should probably make these strings (all the dropdowns) translatable as well.

Schermata 2020-11-16 alle 09 56 10

**Comment by exelban** [comment]
Hi. Yeap. It must be translated as well. But I cannot find time to make it translatable. It's not the text missing in the translations. Just this dropdown is not prepared for translation(

**Pull request merged**
