### PR TITLE
Update Chinese Traditional (Taiwan)

### PR DESCRIPTION
**Pull request by jrthsr700tmax**
[Translate](url) colors for Chinese Traditional (Taiwan).
新增色彩的正體中文（臺灣）翻譯。

———————————————————————

**You can view, comment on, or merge this pull request online at:
您可以在以下連結檢視、留言或線上合併此更新請求：**

> [https://github.com/exelban/stats/pull/438](https://github.com/exelban/stats/pull/438)

**Commit Summary
更新大綱**

- Update Localizable.strings
更新 Localizable.strings 檔案

**File Changes
檔案變更**

- **M** [Stats/Supporting Files/zh-Hant.lproj/Localizable.strings](https://github.com/exelban/stats/pull/438/files) (60)

**Patch Links:
補丁連結:**

https://github.com/exelban/stats/pull/438.patch
https://github.com/exelban/stats/pull/438.diff

### CODE REVIEW

**Comment by kevindiu** [comment]
This is not Traditional Chinese translation, it is Simplified Chinese translation.

**Comment by jrthsr700tmax** [comment]
Dear kevindiu

According your commit, I've checked and translated the name of colors to Traditional Chinese (Taiwan) characters before submit this pull request. You can see the difference radical between "糹" and "纟" of Chinese Characters, character "藍" & "蓝", "黃" & "黄" etc... in this pull request and pull request #437 .

Best Regards

jrthsr700tmax

============================================================
IN CHINESE

此致 kevindiu

根據您的留言，我在提交此更新請求之前，即已經將確認色彩名稱並轉換為正體中文（臺灣）的文字。您可以從這則更新請求與 #437 更新請求中看到中文部首「糹」和「纟」的不同，以及文字「藍」和「蓝」、「黃」和「黄」等字樣的不同。

敬祝
順頌時祺

jrthsr700tmax

**Comment by kevindiu** [comment]
Hi @jrthsr700tmax ,
Thank you for your reply. 

I am really sorry that it was my mistake. 
The system font of my device display the Simplified Chinese character instead of Traditional Chinese even if it is the Traditional Chinese character, I will correct my system setting and review this PR later.

**Review by kevindiu — APPROVED** [review]
LGTM.

**Comment by jrthsr700tmax** [comment]
Dear kevindiu

Don't keep it on mind. There are also many universal (same-shape) characters between Traditional Chinese and Simplified Chinese. It is very hard to recognize between then if people who don’t live in East Asian Cultural Sphere.

Best Regards 

jrthsr700tmax

==============================
IN CHINESE

此致kevindiu

不用介意。在正體中文與簡體中文之間，仍有很多通用（相同形狀）的字符。如果不是生活於漢字文化圈的人，是很難辨識其中的不同的。

敬祝
順頌時祺

jrthsr700tmax

**Pull request merged**
