### PR TITLE
Update Taiwan Traditional Chinese Localization Translate

### PR DESCRIPTION
**Pull request by jrthsr700tmax**
Update Taiwan TC Localization Below:
更新臺灣正體中文最佳化翻譯如下：
* "Check for Update" Options (「檢查更新」之各該選項)
* "Serial Number" & "Uptime" under the "Dashboard" (「儀表板」項下之「序號」及「正常運作時間」)

### CODE REVIEW

**Review by jrthsr700tmax — COMMENTED** [review]
「打開時」change to「打開時檢查」

**Comment by exelban** [comment]
Thanks.

**Comment by exelban** [comment]
Could I add you as a contributor to this translation?)

**Comment by jrthsr700tmax** [comment]
Of course!

**Pull request merged**
