### PR TITLE
[add] Vietnamese language

### PR DESCRIPTION
**Pull request by xuandung38**
hxd.vn from vno hackintosh

### CODE REVIEW

**Comment by exelban** [comment]
Hi.
Thanks for the translation. Can I add you as a contributor to this translation?

I add a few new words a few minutes ago ([commit](https://github.com/exelban/stats/commit/c39b91c0b8e9ed52e1d9953281dabc206cff632c)). Could you please add missing translations?
A few words in the `Battery` section and 2 in the `Words` section.

**Comment by xuandung38** [comment]
Of course! You can add me, but wait me translate new words.

**Comment by xuandung38** [comment]
You should add some missing words like "_sec, enabled, disabled_", I have already added it in my file (in the _Words_ section) and you can delete it if you want. But I think this is necessary

**Comment by exelban** [comment]
Thanks

**Comment by xuandung38** [comment]
You are welcome

**Pull request merged**
