### PR TITLE
Update Chinese Traditional (Taiwan) Translation

### PR DESCRIPTION
**Pull request by jrthsr700tmax**
Update 🇹🇼Taiwan Traditional Chinese Translation File
更新🇹🇼臺灣正體中文翻譯檔案

*Fix the translation of “Support the application” from “支持此應用程式” to “協助此應用程式更臻完美”.（修正「Support the application」之翻譯，由「支持此應用程式」修正為「協助此應用程式更臻完美」。）
*Add translations of “AC Power” and “Battery Power” under the “Battery” Item.（於「電池」項下新增「AC Power」（交流電）及「Battery Power」（電池）之翻譯。）

### CODE REVIEW

**Comment by Tai-Zhou** [comment]
According to the icon of "Support the application" 截屏2021-02-15 上午9 17 51, the meaning of "support" should be sponsor I guess.

**Comment by jrthsr700tmax** [comment]
Thanks for Comment.

I’ve fixed it from “協助此應用程式更臻完美” to “贊助此應用程式”.

Sincerely,
Your best

jrthsr700tmax

—————————
in Chinese

感謝您的留言。

茲業已修正為「贊助此應用程式」。（原為「協助此應用程式更臻完美」）

敬祝
順頌時祺

jrthsr700tmax

**Comment by exelban** [comment]
Hi.
Please use this naming for translation updates: `Update Chinese Traditional translation`.

**Comment by jrthsr700tmax** [comment]
Thanks for Comment.

I’ve changed the title to “Update Chinese Traditional (Taiwan) Translation”.

Sincerely,
Your best.

jrthsr700tmax

—————————
in Chinese

感謝您的留言。

茲業已修正標題為「Update Chinese Traditional (Taiwan) Translation」（更新正體中文（臺灣）翻譯）。

敬祝
順頌時祺

jrthsr700tmax

**Pull request merged**
