### PR TITLE
Update German localization

### PR DESCRIPTION
**Pull request by Fighter456**

### CODE REVIEW

**Comment by LostInCompilation** [comment]
But you left out quite a few... I think I will also make a PR which updates all untranslated entries.

**Comment by Fighter456** [comment]
@LostInCompilation Just point out/translate the missing ones with the suggestion functionality and I will take them over with having you as co-author.

**Comment by LostInCompilation** [comment]
Oh wow never noticed this is possible. Will do it tomorrow, please leave PR open.

**Comment by LostInCompilation** [comment]
Well doesn't work. I can only suggest changes on lines right around your changes. But nothing else farther away. This PR can be closed and merged, I will make a new one after the merge.

**Pull request merged**
