### PR TITLE
add Homebrew install instruction

### PR DESCRIPTION
**Pull request by dawidd6**
Added to Homebrew Cask repo here: https://github.com/Homebrew/homebrew-cask/pull/84790

### CODE REVIEW

**Comment by exelban** [comment]
@dawidd6 thanks for this. 

As I understand homebrew fetch a new version from git tags?
So I don't need to update anything to provide a new version for brew?

**Comment by dawidd6** [comment]
Your program has an auto-update mechanism built-in, so no need to worry about it.

**Comment by exelban** [comment]
Yeap, but I see that they have a `version` inside. And fetching the app from `https://github.com/exelban/stats/releases/download/v#{version}/Stats.dmg`. 

So it means, if I release a new version tomorrow, I will need to update their configuration file. To ensure that users install the latest app via homebrew?

Or it will fetch a new version if there is a new tag in git?

**Comment by exelban** [comment]
Because if they just fetch a specific tag. And not checking for the newest tag. It will be good to add a `latest` tag to git. And use this tag to indicate the last version.

**Comment by dawidd6** [comment]
Yes, the Cask file should be updated, when a new git tag is pushed, but I think it is not too important, because auto-update in the app will always get it to the newest version regardless.

**Comment by exelban** [comment]
Auto-update in Stats app?

**Comment by dawidd6** [comment]
Yes

**Comment by exelban** [comment]
Hmmm, it's not a good look, when someone installs the new app. Open it, and receive the message that a new version is available.

I see two options: create a gh action to make automatically PR to brew, or add `latest` tag.

But still thanks for your help.

**Comment by dawidd6** [comment]
I understand your concern. There is an Action for Homebrew Formulae updating, but sadly not for Casks (or I'm not aware of any).

**Pull request merged**
