### PR TITLE
Add support for Korean translation

### PR DESCRIPTION
**Pull request by escapeanaemia**

### CODE REVIEW

**Comment by exelban** [comment]
Hi. 

Thanks for the translation. Can I add you as a contributor to this translation?

**Comment by escapeanaemia** [comment]
of course! I'm also glad to show me as a contributor :)))
thank you~

**Comment by escapeanaemia** [comment]
Oh plz dont merge now I found wrong translation just now. let me push one more commit

**Comment by exelban** [comment]
Ok, I will merge it tomorrow. Before releasing the new version.

**Comment by escapeanaemia** [comment]
I modified everything. Now you can merge ;)

**Pull request merged**
