### PR TITLE
Add translation support for Japanese

### PR DESCRIPTION
**Pull request by treastrain**
I've heard from my Twitter contacts that this monitor application is very great. I'd like to help by adding Japanese support.

### CODE REVIEW

**Comment by exelban** [comment]
Hi.
Thanks for the translation.
Can I add you as a contributor to this translation?

**Comment by treastrain** [comment]
@exelban Yes!

**Comment by exelban** [comment]
I add a [new option](https://github.com/exelban/stats/blob/a93994f0f2b351354aaaf0aa419eb6fb0af13b20/Stats/Supporting%20Files/en.lproj/Localizable.strings#L100) in the GPU module a few minutes ago. Could add it to the translation?

**Comment by treastrain** [comment]
@exelban It's done! and updated to match the en.lproj/Localizable.strings of a93994f0f2b351354aaaf0aa419eb6fb0af13b20.

**Pull request merged**
