### PR TITLE
Refresh icon network

### PR DESCRIPTION
**Pull request by ppizarror**
Captura de Pantalla 2021-04-13 a la(s) 10 24 41

### CODE REVIEW

**Comment by exelban** [comment]
Hi. Please open an issue before making a PR with the new feature. It allows discussing if a feature needed at all.
Because in your previous PR you propose to add the translation to the `Refresh` button. And now, you remove the feature you proposed before with the new one.

**Comment by ppizarror** [comment]
Ok, I'll create a new issue. Anyway you proposed in the last PR to replace the refresh text into an icon. The refresh translation Is still being used but as an tooltip

**Comment by exelban** [comment]
Opening an issue it's a good option before opening a PR, not after.
PR looks fine, but please move the icon to the ModuleKit.

**Comment by ppizarror** [comment]
> Opening [an issue](https://github.com/exelban/stats/issues/426) it's a good option before opening a PR, not after.
> PR looks fine, but please move the icon to the ModuleKit.

yes, I know; my fault as I've plenty of repos, but I'm not used to work in other's peop projects, sorry for my mistake

**Comment by ppizarror** [comment]
I've moved the icon to ModuleKit package :)

**Pull request merged**
