### PR TITLE
Czech localization

### PR DESCRIPTION
**Pull request by mpl75**
Hello, I've created Czech localization

### CODE REVIEW

**Comment by exelban** [comment]
Hi. Thanks.
It looks ok. I will merge it before the new release.

Can I add you as a contributor to this translation?

**Comment by mpl75** [comment]
Of course, you can, I will be honoured

**Comment by exelban** [comment]
Hi. I [add](https://github.com/exelban/stats/commit/c0888b9f90e2d81c1c8cd859771dde4ad1cd600f) a few missing words to the list. 
Could you add these words to your translation?

**Comment by mpl75** [comment]
Hi, I am little bit confused now, that string "Cycles" was added by you? Yes, czech translation is correct.

____
mp

**Pull request merged**
