### PR TITLE
- enhancement: battery cycle

### PR DESCRIPTION
**Pull request by Military-Doctor**
resolve the conflicts.

You can directly compile and run to see the results.

### CODE REVIEW

**Comment by Military-Doctor** [comment]
**Before**
Xnip2020-12-23_17-56-40
**After**
Xnip2020-12-23_17-55-54
Xnip2020-12-23_17-56-07

**Comment by exelban** [comment]
Hi. Thanks for the battery count.
Hmm, it's an interesting way to show missing GPU temperature. Thanks.

**Comment by Military-Doctor** [comment]
the SMC name of GPU in MacBook Pro 16“ 2019 is quite different 😂, I searched a lot to find it out.

**Comment by Military-Doctor** [comment]
could you please merge this pull request? Thanks~

**Comment by exelban** [comment]
Hi. Ok, I'm going to merge this PR. But please next time make a separate PR for each feature.

**Comment by Military-Doctor** [comment]
Thank you for reminding me, this is my mistake, I will pay attention to it next time.

**Pull request merged**
