### PR TITLE
feat: spell out hours and minutes in battery remaining long format

### PR DESCRIPTION
**Pull request by Atemu**
Fixes https://github.com/exelban/stats/issues/855

### CODE REVIEW

**Comment by exelban** [comment]
Hi. Thanks for the PR.
But it cannot be merged. This text is used in the widget. And it cannot be changed, because then the text will not fit in the item.

**Comment by Atemu** [comment]
Oh! On my machine it fit perfectly...

**Comment by exelban** [comment]
Ok, I have checked that.
And I cannot accept that. This text takes too much space in the menu bar. It's more than almost all of my widgets.

Zrzut ekranu 2022-03-4 o 19 27 48

**Comment by Atemu** [comment]
Oh! Didn't know it could also display in the menu bar, I thought that code was for the popup window only.

That won't work and since the original issue has been closed anyways, I'm going to close this.

**Comment by exelban** [comment]
Still, thanks for your proposal.

**Pull request closed without merging**
