### PR TITLE
lang: Add missing Arabic language sentences and works.

### PR DESCRIPTION
**Pull request by AhmedAbouelkher**
This PR continues on #1780 work to improve the Arabic language localization in the app because it is not complete.

Suggestion: 
I think adding a language change drop-down to the app settings will be great. [This solution](https://github.com/exelban/stats/issues/365#issuecomment-790403616) works but it is not time-efficient or User friendly.

### CODE REVIEW

**Comment by AhmedAbouelkher** [comment]
@exelban Added missing `Fixed scale` to Arabic

**Comment by exelban** [comment]
thx.
And thanks for your contribution.

**Comment by 2B-4G10** [comment]
Arabic translation is done on the Fork
I shared the link earlier today @exelban via email
There might be some overview needed or editing it'd be amazing if you can review it @AhmedAbouelkher

**Review by 2B-4G10 — APPROVED** [review]
Great

**Comment by exelban** [comment]
sorry, forgot to merge this PR( Will be included in the next release.

**Pull request merged**
